/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TodoItem } from "./models/todoItem";
export namespace Components {
    interface AppHome {
        "headerToBeDisplayed": boolean;
    }
    interface AppRoot {
    }
    interface TodoList {
        "todoItems": TodoItem[];
    }
    interface TodoListForm {
        "todoItemsLength": number;
    }
    interface TodoLogo {
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLTodoListElement extends Components.TodoList, HTMLStencilElement {
    }
    var HTMLTodoListElement: {
        prototype: HTMLTodoListElement;
        new (): HTMLTodoListElement;
    };
    interface HTMLTodoListFormElement extends Components.TodoListForm, HTMLStencilElement {
    }
    var HTMLTodoListFormElement: {
        prototype: HTMLTodoListFormElement;
        new (): HTMLTodoListFormElement;
    };
    interface HTMLTodoLogoElement extends Components.TodoLogo, HTMLStencilElement {
    }
    var HTMLTodoLogoElement: {
        prototype: HTMLTodoLogoElement;
        new (): HTMLTodoLogoElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
        "todo-list": HTMLTodoListElement;
        "todo-list-form": HTMLTodoListFormElement;
        "todo-logo": HTMLTodoLogoElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
        "headerToBeDisplayed"?: boolean;
    }
    interface AppRoot {
    }
    interface TodoList {
        "todoItems"?: TodoItem[];
    }
    interface TodoListForm {
        "onInputChange"?: (event: CustomEvent<any>) => void;
        "onSubmit"?: (event: CustomEvent<any>) => void;
        "todoItemsLength"?: number;
    }
    interface TodoLogo {
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-root": AppRoot;
        "todo-list": TodoList;
        "todo-list-form": TodoListForm;
        "todo-logo": TodoLogo;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "todo-list": LocalJSX.TodoList & JSXBase.HTMLAttributes<HTMLTodoListElement>;
            "todo-list-form": LocalJSX.TodoListForm & JSXBase.HTMLAttributes<HTMLTodoListFormElement>;
            "todo-logo": LocalJSX.TodoLogo & JSXBase.HTMLAttributes<HTMLTodoLogoElement>;
        }
    }
}
